package org.debadatta.health.model;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Component
@Entity
@Scope("prototype")
@DynamoDBDocument
public class Appointments {

    @Id
    @DynamoDBAttribute
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    private int a_id;
    @DynamoDBAttribute
    private int p_id;
    @DynamoDBAttribute
    private int d_id;
    @DynamoDBAttribute
    private int a_date;
    @DynamoDBAttribute
    private String a_time;
    @DynamoDBAttribute
    private String status;

    public int getAppointmentId() {
        return a_id;
    }

    public void setAppointmentId(int a_id) {
        this.a_id = a_id;
    }

    public int getPatientId() {
        return p_id;
    }

    public void setPatientId(int p_id) {
        this.p_id = p_id;
    }

    public int getDoctorId() {
        return d_id;
    }

    public void setDoctorId(int d_id) {
        this.d_id = d_id;
    }

    public int getAppointmentDate() {
        return a_date;
    }

    public void setAppointmentDate(int a_date) {
        this.a_date = a_date;
    }

    public String getAppointmentTime() {
        return a_time;
    }

    public void setAppiontmentTime(String a_time) {
        this.a_time = a_time;
    }

    public String getAppointmentStatus() {
        return status;
    }

    public void setAppiontmentStatus(String status) {
        this.status = status;
    }

}
