package org.debadatta.health.model;

import org.debadatta.health.config.AppointmentStatusConverter;
import org.debadatta.health.enums.AppointmentStatus;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import jakarta.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Component
@Scope("prototype")
@DynamoDBTable(tableName = "Appointments")
public class Appointments {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "a_id")
    private String a_id;

    @DynamoDBAttribute(attributeName = "p_id")
    @NotNull(message = "Patient ID can't be null")
    private String p_id;

    @DynamoDBAttribute(attributeName = "d_id")
    @NotNull(message = "Doctor ID can't be null")
    private String d_id;

    @DynamoDBAttribute(attributeName = "a_date")
    private String a_date;

    @DynamoDBAttribute(attributeName = "a_time")
    private String a_time;

    @DynamoDBTypeConverted(converter = AppointmentStatusConverter.class)
    @DynamoDBAttribute(attributeName = "status")
    private AppointmentStatus status;

}