package org.debadatta.health.model;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import jakarta.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Component
@Scope("prototype")
@DynamoDBTable(tableName = "Appointments")
public class Appointments {

    DynamoDBMapper dynamoDBMapper;

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "a_id")
    private String a_id; // Changed from int to String

    @DynamoDBAttribute(attributeName = "p_id")
    @NotNull(message = "Patient ID can't be null")
    private String p_id;

    @DynamoDBAttribute(attributeName = "d_id")
    @NotNull(message = "Doctor ID can't be null")
    private String d_id;

    @DynamoDBAttribute(attributeName = "a_date")
    @NotNull(message = "Appointment date can't be null")
    private String a_date;

    @DynamoDBAttribute(attributeName = "a_time")
    @NotNull(message = "Appointment time can't be null")
    private String a_time;

    @DynamoDBAttribute(attributeName = "status")
    private String status;

}
