package org.debadatta.health.model;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import java.util.*;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Component

@Scope("prototype")
@DynamoDBTable(tableName = "Doctors")
public class Doctors {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "d_id")
    private String d_id;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "password")
    private String password;
    @DynamoDBAttribute(attributeName = "age")
    private int age;
    @DynamoDBAttribute(attributeName = "specialization")
    private String specialization;
    @DynamoDBAttribute(attributeName = "experience")
    private int experience;
    @DynamoDBAttribute(attributeName = "availability")
    private Map<Date, List<String>> availability;

    public boolean isAvailable(Date a_date, String a_time) {

        if (availability.containsKey(a_date)) {
            List<String> availableTimes = availability.get(a_time);
            return availableTimes.contains(a_time);
        }
        return false;

    }

}
