package org.debadatta.health.model;

import lombok.Data;
import lombok.NoArgsConstructor;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;

@Data
@NoArgsConstructor
@Component
@Entity
@Scope("prtotype")
@DynamoDBTable(tableName = "Patients")

public class Patients {

    @Id
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    @DynamoDBAttribute
    private String p_id;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private Integer age;
    @DynamoDBAttribute
    private String disease;
    @DynamoDBAttribute
    private String gender;
    @DynamoDBAttribute
    private String address;
    @DynamoDBAttribute
    private String phone_no;

    public String getId() {
        return p_id;
    }

    public void setId(String p_id) {
        this.p_id = p_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getDisease() {
        return disease;
    }

    public void setDisease(String disease) {
        this.disease = disease;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhoneNo() {
        return phone_no;
    }

    public void setPhoneNo(String phone_no) {
        this.phone_no = phone_no;
    }

}
