package org.debadatta.health.model;

import lombok.Data;
import lombok.NoArgsConstructor;

import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Data
@NoArgsConstructor
@Component
@Scope("prtotype")
@DynamoDBTable(tableName = "Patients")

public class Patients {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "p_id")
    private String p_id;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "password")
    private String password;
    @DynamoDBAttribute(attributeName = "age")
    private Integer age;
    @DynamoDBAttribute(attributeName = "disease")
    private String disease;
    @DynamoDBAttribute(attributeName = "gender")
    private String gender;
    @DynamoDBAttribute(attributeName = "address")
    private String address;
    @DynamoDBAttribute(attributeName = "phone_no")
    private String phone_no;

}
